collection_name: agent
persist_directory: chroma_db
k: 5
data_path: data
md5_hex_store: md5.txt
allow_knowledge_file_type: ["txt"]

chunk_size: 200
chunk_overlap: 20
separators: [ "\n\n", "\n", " ", "","?", "!", ".", "," ,"？", "！", "。", "，"]
